# Generated by Django 3.0.3 on 2020-02-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='suer',
            new_name='user',
        ),
    ]
